### ISSUE TITLE
Requires ruby 2.2?

### ISSUE THREAD

**Issue by natehs** [usertesting/voicebase-client-ruby#9]
Looks like the hash definitions in word.rb require ruby 2.2+:
2.1.5 :001 > require 'voicebase'
SyntaxError: /Users/nate/.rvm/gems/ruby-2.1.5/gems/voicebase-client-ruby-1.2.0/lib/voicebase/json/word.rb:56: syntax error, unexpected ':', expecting =>
      {"p": sequence, "c": confidence, "...
           ^

It looks like just fixing those hash definitions would allow ruby 1.9.3.  But if you want to require 2.2, please document.

**Comment by voxxit** [comment]
@natehs I have an open PR for fixing other versions of Ruby: #10 — it should be merged soon, and a new version cut.

**Comment by voxxit** [comment]
@natehs v1.2.2 has been [released](https://rubygems.org/gems/voicebase-client-ruby/versions/1.2.2), and it includes this fix. Thanks for reporting it!

**Comment by natehs** [comment]
Thank you!
